using System.Collections.Immutable;
using SharpPortico.Generator.Model;

namespace SharpPortico.Generator.Emit;

internal static class CodeEmitter
{
    public static ImmutableArray<(string HintName, string Text)> Emit(GrpcModel model, OpenApiWorkItem item)
    {
        var builder = ImmutableArray.CreateBuilder<(string HintName, string Text)>();

        // 1) Optional .proto descriptor, emitted as a generated class exposing the proto
        //    text as a const string (enables consumers to write it out or validate it).
        if (item.EmitProtoFile)
        {
            var protoText = ProtoEmitter.Emit(model, item);
            var pw = new CodeWriter();
            pw.Line("// <auto-generated>");
            pw.Line("//     Generated by SharpPortico (OpenAPI to gRPC). Do not edit.");
            pw.Line("// </auto-generated>");
            pw.Line("#nullable enable");
            pw.Line();
            pw.Block("namespace " + model.Namespace, () =>
            {
                pw.Line($"public static partial class {model.ServiceName}Proto");
                pw.Line("{");
                pw.Open();
                pw.Line("/// <summary>The .proto descriptor for the generated service.</summary>");
                pw.Line($"public const string Text = \"{EscapeCsString(protoText.Replace("\r\n", "\n"))}\";");
                pw.Close();
                pw.Line("}");
            });
            builder.Add((item.HintName + ".proto.cs", pw.ToString()));
        }

        // 2) Generated C#: protobuf messages + gRPC contract + client + DI.
        var w = new CodeWriter();
        var hint = item.HintName + ".g.cs";
        w.Line("// <auto-generated>");
        w.Line("//     Generated by SharpPortico (OpenAPI to gRPC). Do not edit.");
        w.Line("// </auto-generated>");
        w.Line("#nullable enable");
        w.Line();
        w.Block("namespace " + model.Namespace, () =>
        {
            MessageEmitter.EmitAll(w, model);
            ServiceEmitter.Emit(w, model, item);
        });
        builder.Add((hint, w.ToString()));

        return builder.ToImmutable();
    }

    private static string EscapeCsString(string value)
        => value
            .Replace("\\", "\\\\")
            .Replace("\"", "\\\"")
            .Replace("\t", "\\t")
            .Replace("\r", "\\r")
            .Replace("\n", "\\n");
}
