<Project Sdk="Microsoft.NET.Sdk.Web">

  <PropertyGroup>
    <TargetFramework>$(SharpPorticoNetTargetFramework)</TargetFramework>
    <RootNamespace>SharpPortico.Samples.MinimalApiExample</RootNamespace>
    <OutputType>Exe</OutputType>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <SharpPorticoGeneratorOutDir>$(MSBuildThisFileDirectory)..\..\src\SharpPortico.SourceGenerator\bin\$(Configuration)\$(SharpPorticoGeneratorTargetFramework)\</SharpPorticoGeneratorOutDir>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\..\src\SharpPortico.Abstractions\SharpPortico.Abstractions.csproj" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\..\src\SharpPortico.SourceGenerator\SharpPortico.SourceGenerator.csproj"
                      ReferenceOutputAssembly="false"
                      OutputItemType="Analyzer"
                      PrivateAssets="all" />
    <Analyzer Include="$(SharpPorticoGeneratorOutDir)Microsoft.OpenApi.dll" />
    <Analyzer Include="$(SharpPorticoGeneratorOutDir)Microsoft.OpenApi.Readers.dll" />
    <Analyzer Include="$(SharpPorticoGeneratorOutDir)SharpYaml.dll" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="Google.Protobuf" />
    <PackageReference Include="Grpc.Core" />
    <PackageReference Include="Grpc.Core.Api" />
    <PackageReference Include="Grpc.Net.Client" />
    <PackageReference Include="Microsoft.Extensions.DependencyInjection" />
  </ItemGroup>

  <ItemGroup>
    <AdditionalFiles Include="openapi/**/*.yaml" />
  </ItemGroup>

  <ItemGroup>
    <Compile Remove="Generated/**/*.cs" />
    <None Include="Generated/**/*.cs" />
  </ItemGroup>

</Project>