<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>$(SharpPorticoNetTargetFramework)</TargetFramework>
    <RootNamespace>SharpPortico</RootNamespace>
    <IsPackable>true</IsPackable>
    <Description>Tiny AOT-safe runtime helpers used by SharpPortico-generated gRPC code.</Description>
    <PackageId>SharpPortico.Runtime</PackageId>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Google.Protobuf" />
    <PackageReference Include="Grpc.Core.Api" />
    <PackageReference Include="Microsoft.Extensions.Caching.Abstractions" />
    <PackageReference Include="Microsoft.Extensions.Caching.Memory" />
    <PackageReference Include="Microsoft.Extensions.Configuration.Abstractions" />
    <PackageReference Include="Microsoft.Extensions.DependencyInjection.Abstractions" />
    <PackageReference Include="Microsoft.Extensions.Logging.Abstractions" />
    <PackageReference Include="System.Text.Json" />
    <PackageReference Include="Microsoft.Extensions.Http" />
  </ItemGroup>

</Project>